//   const contactDetails = await rest_api_call('contacts/search/2','post',{
//     "locationId": getLocationId(),
//     "page": 1,
//     "pageLimit": 20,
//     "sort": [],
//     "filters": [
//         {
//             "group": "OR",
//             "filters": []
//         }
//     ],
//     "searchAfter": [
//         1699445261368,
//         "RFfs4fG2WLR3fFxT34i5"
//     ]
// })

const contactData = [
  {
    id: "fpz4Lrgx8ILXGyy1V72J",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "abraham peter",
    firstName: "abraham",
    lastName: "peter",
    companyName: null,
    email: "abrahampeter@hexatechsolution.com",
    phone: null,
    dnd: false,
    type: "lead",
    source: "asgd",
    assignedTo: "cMzSNQKNBDRoYyMTytQV",
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-20T18:31:52.376Z",
    dateUpdated: "2023-11-21T12:00:39.140Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    lastActivity: 1700565857070,
    customFields: [],
  },
  {
    id: "Y5pTgF6y8hdxdJtYfzco",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-10T04:20:45.880Z",
    dateUpdated: "2023-11-10T04:20:48.504Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "EsQjl3Sv92hPDO2gWbRd",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-10T04:20:45.879Z",
    dateUpdated: "2023-11-10T04:20:47.792Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "TV3FZenSUkVDmMLFC4YU",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:09:06.590Z",
    dateUpdated: "2023-11-08T12:09:08.523Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "rTaMWjkjlT6HzpF0kMC1",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:09:05.904Z",
    dateUpdated: "2023-11-08T12:09:08.239Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "tPzW3hfTDmdz2GCGBubi",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:08:07.091Z",
    dateUpdated: "2023-11-08T12:08:08.915Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "Z1boCIvWf7K0kg9lfdX3",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:08:05.879Z",
    dateUpdated: "2023-11-08T12:08:07.952Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "fI6KApVJljHsGf06J1ZC",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:08:05.451Z",
    dateUpdated: "2023-11-08T12:08:08.280Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "ut7pSngkdKzeZUhb59bz",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:08:04.870Z",
    dateUpdated: "2023-11-08T12:08:06.652Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "fJ5kXcXeuUrRRYZ0dCSQ",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:57.028Z",
    dateUpdated: "2023-11-08T12:07:58.892Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "iXkvkQWR7E6HJI3F6nif",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:56.879Z",
    dateUpdated: "2023-11-08T12:07:58.590Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "sA3jw6pP7mISehG2W59X",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:53.832Z",
    dateUpdated: "2023-11-08T12:07:55.619Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "2jRNnJ8KoFTzZa5SXmVc",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:52.904Z",
    dateUpdated: "2023-11-08T12:07:54.664Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "OcCLa95GtCZPxbQ4Kuk9",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:51.007Z",
    dateUpdated: "2023-11-08T12:07:52.903Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "oMbT5FEWf8DdwaPcKNGJ",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:50.892Z",
    dateUpdated: "2023-11-08T12:07:52.732Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "6kSYrFV1B0Pqlue3HySY",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:47.854Z",
    dateUpdated: "2023-11-08T12:07:49.558Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "sRnrDnkAliYW3KPKIjxq",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:46.852Z",
    dateUpdated: "2023-11-08T12:07:48.552Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "kGI8SSJFf1N5EFz0ye3r",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:46.163Z",
    dateUpdated: "2023-11-08T12:07:47.927Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "vHFkh20pUFTEkTQSrSuY",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:44.912Z",
    dateUpdated: "2023-11-08T12:07:46.691Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
  {
    id: "RFfs4fG2WLR3fFxT34i5",
    locationId: "Q6sATpsoSLCPFf5ErtoF",
    contactName: "",
    firstName: null,
    lastName: null,
    companyName: null,
    email: null,
    phone: null,
    dnd: false,
    type: "lead",
    source: "file uploader",
    assignedTo: null,
    city: null,
    state: null,
    postalCode: null,
    address1: null,
    dateAdded: "2023-11-08T12:07:41.368Z",
    dateUpdated: "2023-11-08T12:07:43.604Z",
    dateOfBirth: null,
    businessId: null,
    tags: [],
    followers: [],
    country: "IL",
    additionalEmails: [],
    linkedInLeadId: null,
    clientPortalId: null,
    customFields: [],
  },
];

const finalArray = contactData.map((item) => {
  return [
    item.contactName,
    item.phone,
    item.email,
    item.dateAdded,
    item.lastActivity,
    item.tags.join(","),
  ];
});

console.log(finalArray, " finalArray");

const Grid = gridjs.Grid;

new Grid({
  // columns: ["Name", "Phone", "Email", "Created", "LastActivity", "Tags"],
  columns: [
    { name: "Name", sort: true },
    { name: "Phone", sort: true },
    { name: "Email", sort: true },
    { name: "Created", sort: true },
    { name: "LastActivity", sort: true },
    { name: "Tags", sort: false },
  ],
  data: finalArray,
}).render(document.getElementById("wrapper"));

const checkboxTag = document.querySelectorAll(".my-checkbox");

checkboxTag.forEach((item) => {
  item.addEventListener("click", (e) => {
    console.log("checkbox checked", e.target.checked);
  });
});
